[package]
name = "rszmp"
version = "0.1.0"
edition = "2021"
authors = ["odd <odd12258053@gmail.com>"]

[dependencies]
libc = "0.2.119"

[dev-dependencies]
uuid = { version = "0.8.2", features = ["v4"] }
